### ISSUE TITLE
Text-api conflict with other plugins

### ISSUE THREAD

**Issue by OcZi** [unnamed/CommandFlow#6]
Every time i try to load a plugin that uses text-api,
CommandFlow throws a IllegalAccessError: 

- https://paste.md-5.net/ujomemaxob.coffeescript

but it disappears if i remove any of the conflicting plugins.

**Comment by FixedDev** [comment]
It's not a problem with CommandFlow.
You should at least relocate the text-API since we're not using a mainstream version, we're using a modified stripped version that has an api binary compatible with the mainstream 3.0.0, if you want the complete version just exclude the version included with CommandFlow and use the mainstream one
